### ISSUE TITLE
Inaccurate Comments/Docs.

### ISSUE THREAD

**Issue by duplexsystem** [Bevy-Rust-GPU/rust-gpu-bridge#2]
I was looking through the code and found many instances where this particular comment template with not accurate with what the file actually did.

https://github.com/Bevy-Rust-GPU/rust-gpu-bridge/blob/0e739b1396b47c8751592bbdbddb546aadc538b3/src/cos.rs#L9

Example ^

I assume this is a byproduct of Ctrl+C/Ctrl+V but I figured I'd know :)

**Comment by ProfLander** [comment]
It is, yeah - fixing it has been at the back of my mind for a little while, so I've done a `cargo doc` niceness sweep.

Also, the math traits are now exposed at the root instead of via prelude, which should make things a bit more tidy.
